# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_request',
            old_name='fufillmentDate',
            new_name='fulfillmentDate',
        ),
    ]
