# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20170401_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment_method',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='security',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping_address',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Billing_Address',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Payment_Method',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
        migrations.DeleteModel(
            name='Service_Request',
        ),
        migrations.DeleteModel(
            name='Shipping_Address',
        ),
    ]
