# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_auto_20170401_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('productID', models.IntegerField(primary_key=True, serialize=False)),
                ('productType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Settings_of_interst',
            fields=[
                ('interestID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='emailID',
            new_name='primaryEmailID',
        ),
        migrations.AddField(
            model_name='customer',
            name='preferredContact',
            field=models.CharField(default='primaryEmail', max_length=1000),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondaryEmailID',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='settings_of_interst',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer'),
        ),
        migrations.AddField(
            model_name='settings_of_interst',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Product_type'),
        ),
    ]
