# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=19940625, max_length=20),
            preserve_default=False,
        ),
    ]
